name: 'Envato Publisher'
description: 'Github Action Which Publishes Final Source Code To Envato FTP'
author: 'varunsridharan'
branding:
  icon: 'hard-drive'
  color: 'green'
inputs:
  ENVATO_USERNAME:
    description: 'Envato.com Account Username'
    default: ''
  ENVATO_PERSONAL_TOKEN:
    description: 'Envato.com Account Personal Access Token'
    default: ''
  DIST_IGNORE:
    description: 'Add file / folders that you wish to exclude from final list of files to be sent to ftp. Eg development files. Final value of this var is expected to be a string delimited with spaces. Eg: ".gitignore package.json README.md" Please Note, excluded file/folder path, is considered from the root of repository unless CUSTOM_PATH is provided, in which case excluded file/folder path should be relative to the final source of files.'
    default: ''
  ASSETS_PATH:
    description: 'Local Assets Path'
    default: '.envatoassets'
  ASSETS_IGNORE:
    description: 'Add file / folders that you wish to exclude from final list of files to be sent to ftp. Eg development files. Final value of this var is expected to be a string delimited with spaces. Eg: ".gitignore package.json README.md" Please Note, excluded file/folder path, is considered from the root of repository unless CUSTOM_PATH is provided, in which case excluded file/folder path should be relative to the final source of files.'
    default: ''
  DIST_LOCATION:
    description: 'Provide a path here final zip file can be stored. which can be used by other actions.'
    default: 'dist/'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ENVATO_USERNAME }}
    - ${{ inputs.ENVATO_PERSONAL_TOKEN }}
    - ${{ inputs.DIST_IGNORE }}
    - ${{ inputs.ASSETS_PATH }}
    - ${{ inputs.ASSETS_IGNORE }}
    - ${{ inputs.DIST_LOCATION }}
